---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- projects/abundance.md
- projects/abundant-waterfall.md
- projects/acrylic.md
- projects/charcoal.md
- projects/desert-sun.md
- projects/dream-on.md
- projects/fire-lily.md
- projects/gouache.md
- projects/love.md
- projects/namma-thottam-my-garden.md
- projects/pencil.md
- projects/tropical-forest.md
- projects/water.md
- projects/zen-garden.md
