---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: text
  name: buy_link
  label: Buy link
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- projects/21st-century.md
- projects/abundance.md
- projects/abundant-waterfall.md
- projects/accommodate.md
- projects/alone.md
- projects/blossom.md
- projects/cacophony.md
- projects/colourless.md
- projects/cycle-of-life.md
- projects/desert-sun.md
- projects/dream-on.md
- projects/fear.md
- projects/fire-lily.md
- projects/for-you.md
- projects/freedom.md
- projects/inner-peace.md
- projects/lost-treasures.md
- projects/love.md
- projects/namma-thottam-my-garden.md
- projects/new-beginnings.md
- projects/nocturnal.md
- projects/opulence.md
- projects/pensive.md
- projects/safe-space.md
- projects/sparrow.md
- projects/summer.md
- projects/tai-tai.md
- projects/the-minimalist.md
- projects/tropical-forest.md
- projects/village-street.md
- projects/zen-garden.md
